config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :bookings, only: %i[index show]
  resources :bikes, only: %i[new create index show] do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[update]
  get "my_bikes", to: "bikes#bikes_owner"
  get "my_bookings", to: "bookings#bookings_owner"
  # get '/bookings/:id/', to: "bookings#new"
  # get "bookings", to: "bookings#bookings/new/create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  enum category: { road: 0, mountain: 1, electric: 2 }
  enum size: { adult: 0, junior: 1 }

  validates :name, presence: true
  validates :category, presence: true, inclusion: { in: categories.keys, message: "{value} is not valid." }
  validates :size, presence: true, inclusion: { in: sizes.keys, message: "{value} is not valid." }
  validates :price, presence: true
  validates :address, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  # validates :bookingnStatus, inclusion: { in: reservationStatuses }
  # validates :checkOutTime, presence: true
  # validates :expectedReturnTime, presence: true
  belongs_to :user
  belongs_to :bike
  has_many :bikes, dependent: :destroy
  enum status: { pending: 0, confirmed: 1, rejected: 2, started: 3, completed: 4 }
  validates :status, inclusion: { in: statuses.keys, message: "is not valid." }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bikes, dependent: :destroy
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name owner longitude latitude])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name owner longitude latitude])
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit]

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    if @bike.save
      redirect_to my_bikes_path
    else
      puts @bike.errors.messages
      render :new, status: :unprocessable_entity
    end
  end

  def index
    tripstart = Date.parse params[:tripstart]
    tripend = Date.parse params[:tripend]
    cookies[:tripstart] = tripstart
    cookies[:tripend] = tripend
    location = params[:bike][:address]
    if location.present?
      bikes = Bike.near(location, 30)
      @bikes = bikes.select do |bike|
        bike.bookings.each do |booking|
          if booking != "rejected"
            interval_search = tripstart..tripend
            interval_booking = booking.start_at..booking.end_at
            interval_booking.overlaps? interval_search
          end
        end
      end
      puts(@bikes)
    else
      @bikes = Bike.all
    end
  end

  def show
    if @bike.photo.key
      @image_result = @bike.photo.key
    else
      @image_result = "No Image"
    end
  end

  def bikes_owner
    @bikes = Bike.where(user_id: current_user)
  end

  private

  def bike_params
    params.require(:bike).permit(
      :name,
      :category,
      :size,
      :price,
      :address,
      :picture_url,
      :description,
      :lat,
      :lon,
      :title,
      :body,
      :photo
    )
  end

  def set_bike
    @bike = Bike.find(params[:id])
  end
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController

  # Time.zone = 'Central European Time (CET)'

  # before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  before_action :logged_in_user, only: [:show, :edit, :index, :new, :create, :destroy]
  before_action :logged_in_as_admin, only: [:destroy]
  before_action :can_destroy, only: [:destroy]

  # def index
  #   @booking = Booking.all
  #   # bookings = Booking.order(customer_name:)
  # end

  # def show
  #   @booking = Booking.find(params[:id])
  # end

  def new
    @booking = Booking.new
  end

  # def edit
  #   @booking = Booking.find(params[:id])
  # end

  # def create
  #   # bike_id = booking_params[:bike_id]
  #   # user_id = booking_params[:user_id]
  #   @booking = Booking.new(booking_params)

  #   if @booking.save
  #     redirect_to @booking
  #   else
  #     render :new, status: { bookings: booking }
  #   end
  # end


  # def update
  #   @booking = Booking.find(params[:id])

  #   if @booking.update(booking_params)
  #     redirect_to @booking
  #   else
  #     render :new, status: { bookings: booking }
  #   end
  # end

  # def destroy
  #   @booking = Booking.find(params[:id])
  #   @booking.destroy

  #   redirect_to root_path, status: :see_other
  # end

  # def pickup
  #   @booking = Booking.find(params[:id])
  #   if @booking.checkOutTime
  # end



  # private
  # def booking_params
  #   params.require(:booking).permit()
  # end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit]

  # before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # before_action :logged_in_user, only: [:show, :edit, :index, :new, :create, :destroy]
  # before_action :logged_in_as_admin, only: [:destroy]
  # before_action :can_destroy, only: [:destroy]

  def index
    @booking = Booking.all
    # bookings = Booking.order(customer_name:)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @bike = Bike.find(params[:bike_id])
  end

  def create
    @booking = Booking.new
    # @booking = Booking.new(params[:id])
    @bike = Bike.find(params[:bike_id])
    @booking.bike = @bike
    @booking.status = :pending
    @booking.user = current_user
    if @booking.save
      flash[:notice] = "Bike booked!"
      redirect_to new_bike_booking_path(@booking)
    else
      flash[:alert] = "Bike not available!"
      render :new, status: :unprocessable_entity
    end
  end

  def bookings_owner
    @bookings = Booking.joins(bike: :user).where(bike: { user: current_user })
  end

  # def edit
  #   @booking = Booking.find(params[:id])
  # end



  def update
    @booking = Booking.find(params[:id])

    if @booking.update(status: params[:status])
      redirect_to my_bookings_path
    else
      render :new, status: { bookings: booking }
    end
  end

  # def destroy
  #   @booking = Booking.find(params[:id])
  #   @booking.destroy

  #   redirect_to root_path, status: :see_other
  # end

  private

  def booking_params
    params.require(:booking).permit
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_form.html.erb
<div class="container" class = "project">
  <%= simple_form_for (bike) do |f| %>
    <%= f.input :name %>
    <%= f.input :category, collection: Bike.categories.keys %>
    <%= f.input :size, collection: Bike.sizes.keys %>
    <%= f.input :price %>
    <%= f.input :address,input_html: {data: {address_autocomplete_target: "address"},class: "d-none"},
                      wrapper_html: {data: {controller: "address-autocomplete",
                      address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
    <%= f.input :photo, as: :file %>
    <%= f.input :description %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/bikes/bikes_owner.html.erb
<h1>My published bikes</h1>
<div class="card-bike-index-cards">
  <%@bikes.each do |bike|%>
    <div class="card" style="width: 18rem;">
      <%= cl_image_tag bike.photo.key %>
      <div class="card-body">
        <h5 class="card-title"> <%=bike.name%> </h5>
        <p class="card-text"> <%=bike.user.first_name%>  <%=bike.user.last_name%> </p>
        <p class="card-text"> <%=bike.category%> </p>
        <p class="card-text"> <%=bike.price%> </p>
        <p>Owner: <%= "#{bike.user.first_name} #{bike.user.last_name}" %></p>
        <%= link_to "See", bike_path(bike) %>
      </div>
    </div>
  <%end%>
</div>

app/views/bikes/index.html.erb
<div class="card-bike-index-main d-flex p-2 ">
  <h1>All bikes</h1>
  <div class="card-bike-index-cards">
    <% @bikes.each do |bike| %>
      <div class="card-bike-index-card w-100">
        <% if bike.photo.present? %>
          <%= cl_image_tag bike.photo.key %>
        <% end %>
        <div class="bike-info">
          <%if user_signed_in?%>
            <%= link_to bike.name.capitalize(), new_bike_booking_path(bike) %>  <!--bike_path(bike)-->
          <%else%>
            <%= link_to bike.name.capitalize(), new_user_session_path %>  <!--log path-->
          <%end%>
          <p><%= bike.price %>.-/day</p>
          <p>Owner: <%= "#{bike.user.first_name} #{bike.user.last_name}" %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bikes/new.html.erb
<div>
  <div>
    <%= render "form", bike: @bike %>
  </div>
</div>

app/views/bikes/show.html.erb
<p class="mb-2">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <div class="project-info-box mt-0">
          <h1><%= @bike.name.upcase() %></h1>
          <p class="mb-0"> <%= @bike.description %> </p>
        </div>
        <!-- / project-info-box -->
        <div class="project-info-box">
          <p><b>Location:</b> <%= @bike.address %> </p>
          <p><b>Category:</b> <%= @bike.category %></p>
          <p><b>Size:</b> <%= @bike.size %></p>
          <p><b>Price:</b> <%= @bike.price %>.- /day</p>
          <p><b>Owner:</b> <%= "#{@bike.user.first_name} #{@bike.user.last_name}" %></p>
          <p class="mb-0">
          </div>
          <!-- / project-info-box -->
          <div class="project-info-box mt-0 mb-0">
            <p class="mb-0">
              <span class="fw-bold mr-10 va-middle hide-mobile">Share:</span>
              <a href="#x" class="btn btn-xs btn-facebook btn-circle btn-icon mr-5 mb-0"><i class="fab fa-facebook-f"></i></a>
              <a href="#x" class="btn btn-xs btn-twitter btn-circle btn-icon mr-5 mb-0"><i class="fab fa-twitter"></i></a>
              <a href="#x" class="btn btn-xs btn-pinterest btn-circle btn-icon mr-5 mb-0"><i class="fab fa-pinterest"></i></a>
              <a href="#x" class="btn btn-xs btn-linkedin btn-circle btn-icon mr-5 mb-0"><i class="fab fa-linkedin-in"></i></a>
            </p>
          </div>
          <!-- / project-info-box -->
        </div>
        <!-- / column -->
        <div class="col-md-7">
          <%= cl_image_tag @bike.photo.key %>
          <div class="project-info-box">
            <p><b>Number of Bookings:</b> <%= @bike.number_of_bookings %> </p>
          </div>
          <!-- / project-info-box -->
        </div>
        <!-- / column -->
      </div>
    </div>
    <!--INITIAL PICTURE
    <img src=<%=@bike.picture_url%> alt="project-image" class="rounded show-bike-img">
    -->

app/views/bookings/bookings_owner.html.erb
<h1>My Bookings as owner</h1>
<div class="card-bike-index-cards">
  <%@bookings.each do |booking|%>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"> Booking </h5>
        <p class="card-text">start: <%=booking.start_at%>
          <p class="card-text">end: <%=booking.end_at%>
            <p class="card-text">status: <%=booking.status%> </p>
            <div class="d-flex justify-content-between w-100">
              <% if booking.status == "pending" %>
                <%= button_to "accept", booking_path(booking), method: :put, params: {status: :confirmed}, class: "btn btn-success" %>
                <%= button_to "reject", booking_path(booking), method: :patch, params: {status: :rejected, start_at: :nil, end_at: :nil}, class: "btn btn-outline-danger" %>
              <% end %>
              <%= link_to "See", new_bike_booking_path(booking.bike), class: "btn btn-info" %>
            </div>
          </div>
        </div>
      <%end%>
      <%=%>
    </div>

app/views/bookings/new.html.erb
<h2 class="title text-center p-3">Observe ce magnifique vélo, et réserve le pour en profiter un max!</h2>
<div class="container">
  <div class="img-fluid shadow p-3 rounded-4 d-flex justify-center" alt="Responsive image">
    <% if @bike.photo.present? %>
      <%= cl_image_tag @bike.photo.key, crop: :fill, class:"w-100"%>
    <% end %>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <br>
      <br>
      <h4 class="text-justify align mb-5">
        <ul style="list-style: none;"></ul>
        <li class="my-4 list-unstyled"><em>User Name: </em><%=@bike.user.first_name%> <%=@bike.user.last_name%></li>
        <li class="my-4 list-unstyled"><em>Brand Bike: </em><%=@bike.name%></li>
        <li class="my-4 list-unstyled"><em>Category: </em><%=@bike.category%></li>
        <li class="my-4 list-unstyled"><em>Size: </em><%=@bike.size%></li>
        <li class="my-4 list-unstyled"><em>Location: </em><%=@bike.address%></li>
      </h4>
    </div>
    <% unless current_user.owner?%>
      <div class="col-sm-4 my-4">
        <br>
        <div class="shadow p-3 mb-5 bg-white rounded-4">
          <h2 class="text-center list-unstyled"><em> Summary </em></h2>
          <h5 class=" m-2 list-unstyled">From: <%= cookies[:tripstart] %></h5>
          <h5 class=" m-2 list-unstyled">Til: <%=cookies[:tripend]%></h5>
          <%  tripstart = Date.parse cookies[:tripstart]%>
          <%  tripend = Date.parse cookies[:tripend]%>
          <h5 class=" m-2  list-unstyled">Total $ <%= (tripend.mjd - tripstart.mjd + 1) * @bike.price%></h5>
          <div class="text-center">
            <%= simple_form_for [@bike, @booking] do |f| %>
              <%= f.submit class: "btn btn-primary rounded-4" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikesRental</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="d-flex flex-column pt-4" id="home-background">
  <div>
    <h1 class="text-center" style="color: black; text-shadow: 2px 0 #fff, -2px 0 #fff, 0 2px #fff, 0 -2px #fff,
            1px 1px #fff, -1px -1px #fff, 1px -1px #fff, -1px 1px #fff">Welcome on bikes rental</h1>
    <h2 class="text-center" style="color: black; text-shadow: 2px 0 #fff, -2px 0 #fff, 0 2px #fff, 0 -2px #fff,
            1px 1px #fff, -1px -1px #fff, 1px -1px #fff, -1px 1px #fff">The first bike rental website between individuals !</h2>
  </div>
  <div class="flex-grow-1">
    <div class="d-flex h-100 align-items-center justify-content-center">
      <nav class="navbar navbar-light">
        <%= render "shared/search-form" %>
      </nav>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <% if current_user.owner?%>
            <li class="nav-item active">
              <%= link_to "Add bike", new_bike_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "My published bikes", my_bikes_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "My owner bookings", my_bookings_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <%= image_tag "user-login-32.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "My profil", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search-form.html.erb
<div class="search-bar">
  <%= simple_form_for :bike, url: bikes_path, class: "-webkit-box", method: :get do |f|%>
    <%= f.input :address,
                label: false,
                input_html: {data: {address_autocomplete_target: "address"},class: "d-none"},
                wrapper_html: {data: {controller: "address-autocomplete",
                address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
    <div class="d-flex">
      <%= f.input :start_at, label: false,
                            input_html: { type:"date",
                                          id:"start",
                                          name:"tripstart",
                                          value: Date.today,
                                          min:"2022-08-25",
                                          max:"2022-12-31"}%>
      <%= f.input :end_at, label: false,
                          input_html: { type:"date",
                                        id:"start",
                                        name:"tripend",
                                        value: Date.today,
                                        min:Date.today,
                                        max:Date.today.month + 12}%>
    </div>
    <%= f.submit "Search", class: "btn btn-dark btn-search rounded-4" %>
  <% end %>
</div>
</div>